version: '3.9'

services:
  elev-app:
    container_name: elev-ii
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm i && npm run build && npm run dev"
    networks:
      - site
    restart: unless-stopped

networks:
  site:
    driver: bridge
    external: true
